name: Mecha
version: '${project.version}'
main: me.oliver193.mecha.Mecha
api-version: 1.18
authors: [ oliver193 ]
description: Mecha Plugin
website: https://github.com/oliver193/Mecha-Plugin
commands:
  heal:
    permission: mecha.heal
    description: Heal yourself.
    usage: /<command>
  feed:
    permission: mecha.feed
    description: Feed yourself.
    usage: /<command>
  fly:
    permission: mecha.fly
    description: Enable or disable flight!
    usage: /<command>
  mecha:
    description: Displays information about the plugin.
    usage: /<command>